### ISSUE TITLE
Format du code postal

### ISSUE THREAD

**Issue by caliendojulien** [AnnaAgeneau/quelMedecin#1]
https://github.com/AnnaAgeneau/quelMedecin/blob/28c7cd57af2cf0fd185567fa9af0f1b7f2ffe680/src/fr/eni/quelMedecin/bo/Adresse.java#L52

Si vraiment tu veux conserver cette façon de faire, tu peux utiliser : 
```java
int nbreDeChiffre = (int) Math.log10(unChiffre) +1;
``` 
Le logarithme en base 10 permet de connaître le nombre de chiffre d'un nombre. Donc tu n'es pas obligé de convertir *unChiffre* en String pour calculer sa longueur.

**Comment by AnnaAgeneau** [comment]
ok.. merci :)
